spring.application.name=hotelsurvey

# configuracao com o postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/survey_db
spring.datasource.username=survey_user
spring.datasource.password=surveyDB123@

# configuracao do JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.ai.openai.enabled=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# configuracao da aplicacao (para JWT)
app.jwt-secret=KEYKEYSECRETTokensJWT-@KEY@KEY%KeYASLSABO@SECRETKEYCASKEY$$$KEY-1##KEY
app.jwt-expiration-milliseconds=86400000
logging.level.org.springframework.security=DEBUG
